### ISSUE TITLE
VAGGAPATH proposal

### ISSUE THREAD

**Issue by cablehead** [tailhook/vagga#14] opened 2015-03-07 01:59 UTC
Not sure if this is a good idea.

A current use case we have is a base lib repo, which has a vagga.yaml that compiles the lib, and moves it into the container's /usr/lib. We then have other projects which use this lib.

One way to handle this would be to use a shared build path, via the settings.yaml. cd into the lib repo, run vagga _build libcontainer. Then for dependent projects, duplicate the container portion of vagga.yaml from the lib repo - and then define new containers that specify ```!Container libcontainer``` as their base.

The duplication is needed so the right hash can be generated for libcontainer.

I'm thinking through the idea of a VAGGAPATH environment variable. This would be a colon separated list of paths to search for vagga.yaml's.  In the above case, if you ran ```VAGGAPATH=~/git/lib vagga _build subproject``` your subproject could source ```!Container libcontainer```, without defining that container in its own vagga.yaml. Potentially, if you don't set up a shared build directory via settings.yaml, the build could be picked up directly from ~/git/lib/.vagga as well. <-- that in particular might not be a good idea.

**Comment by tailhook** [comment] 2015-03-07 11:39
Well, I have few use cases for subprojects too. I have done it partly as part of ``!SubConfig`` command. Hovewer, it doesn't solve your problem yet, because it doesn't allow reuse already built container. 

Still what I'm trying to obey for vagga:

1. Build must be self-contained. I.e. ``vagga run`` should work from the fresh checkout of a project without additional system setup
2. Contained process can only see it's own project directory and containers, so that it can't mess with other projects on your development machine (i.e. I'm trying to do my best to make running untrusted projects secure, at least by design)

So reusing container from different project should be merely an optimization. I can imagine config like this:
```
setup:
- !SubConfig
    source: !Git git://github.com/some/library
    path: vagga.yaml
    container: library_installed
- ...
```
Then, probably you can write in your ``settings.yaml``:
```
sources:
  git://github.com/some/library: /home/user/git/lib
```

What do you think?

**Comment by cablehead** [comment] 2015-03-08 23:08
I think it's important to stick with those rules. I really like how lightweight Vagga feels, and it comes from that philosophy.

Just trying to understand: what would happen if you don't specify the path to the git repo you your settings.yaml?

Is it necessary to specify ```path: vagga.yaml``` in the SubConfig - trying to think when it'd ever not be a standard vagga.yaml layout in the dependent repository.

**Comment by tailhook** [comment] 2015-03-09 11:13
> Just trying to understand: what would happen if you don't specify the path to the git repo in your settings.yaml?

It will checkout the repository somewhere inside ".vagga" dir, and build container for you.

> Is it necessary to specify path: vagga.yaml in the SubConfig - trying to think when it'd ever not be a standard vagga.yaml layout in the dependent repository.

It is necessary if you have multiple subdirectories with vagga.yaml in dependent repository (it's occasionally useful). Sure, we can have a default value.

**Comment by cablehead** [comment] 2015-03-09 19:04
Gotcha. This sounds great. Is there something I can help with to get it out? :)

**Comment by tailhook** [comment] 2015-10-11 00:05
Closing this in favor of #84 which describes the task better for now.

**Closed by tailhook** 2015-10-11 00:05 UTC
Labels: enhancement
