### ISSUE TITLE
Vagga v0.4.0, 'index out of bounds' panick on a very simple vagga config

### ISSUE THREAD

**Issue by lilianmoraru** [tailhook/vagga#104] opened 2015-10-28 17:23 UTC
Vagga v0.4.0
Ubuntu 15.10 64-bit
uidmap (4.1.5.1-1.1ubuntu7) : [user]:100000:65536

Can't exactly explain how you could replicate this, but I will try to provide as much info as I can.
1. I ran vagga at home(Kubuntu 15.10 64-bit, I think raid0, will re-test and update) and it worked ok
2. I have the issue at work where I connect to the internet through a proxy(Does anything have to do with one-another? I don't know)
3. I run Ubuntu Server 15.10 64-bit(installed later kubuntu-desktop package). It's basically a fresh install
I installed Ubuntu Server because I had to create a raid0 out of 2 HDDs(issue? Don't know).
/dev/md0 - (sda1, sdb1), ext4, root
/dev/md1 - (sda2, sdb2), swap
4. Obviously, as with 15.04 and 15.10 that I tried at home, I had to manually install the "uidmap" package.

Here is the configuration file:
```
containers:
  ubuntu:
    setup:
    - !UbuntuRelease { version: 15.10 }


commands:
  ubuntu: !Command
    container: ubuntu
```
Here is the output(had to hide some info but should be ok):
![vagga_issue_marked](https://cloud.githubusercontent.com/assets/621738/10796142/81210562-7da5-11e5-8087-d54122d7dcd1.png)

Note, ftp doesn't go through localhost, it goes through a server in Germany. We can't always download whatever we want, the server downloads it, checks for viruses and then we can download from server.

**Comment by tailhook** [comment] 2015-10-28 17:54
Hi. The last command is "Permission denied" because `vagga _run ubuntu` is equivalent to `vagga _run ubuntu ""` i.e. an empty command-line, which is treated as `/bin/` (note empty file name), which is a directory, and you can't execute a directory (should probably fixed on its own #105, but it will not solve your issue).

The `vagga ubuntu` builds container well (so downloading a file is not a problem). But can't run a command because of some bug in vagga. It would be nice if you could show the command ubuntu section of your `vagga.yaml` or try to reproduce it on smaller example (i.e. it probably some list there is empty or similar, just replace every letter with `x` or something like this should keep bug reproducible).

Also running with `RUST_BACKTRACE=1 vagga ubuntu` would be helpful (if you use vagga from testing)

**Comment by lilianmoraru** [comment] 2015-10-30 14:10
That was the entire config file "vagga.yaml".
Btw, I tried at home and "vagga _run ubuntu" shows me the available commands while at work it throws that error.
Also, with this config file, at work and at home when I try to do "apt-get update" it tells me that the "lock" file is locked. The usual "rm -f /var.../lock" says that the file system is in read-only mode and when trying to do "mount - / -oremount,rw" says that I don't have the rights...
What's strange, the machine at home was working with vagga 0.3(I tried this now on vagga 0.4 and beta versions)...

**Comment by tailhook** [comment] 2015-11-01 23:21
Okay, I realized that this is issue with validation of configuration file. I.e. you didn't have "run" parameter.

The read-only file system is expected. You may run with `http://vagga.readthedocs.org/en/latest/commands.html#opt-write-mode` or `vagga _run --writable` to get a temporary copy, but all your package installations will be cleaned on container restart.

It's expected that you should install all the packages as part of `setup`, unless you test package installation.

**Comment by lilianmoraru** [comment] 2015-11-02 09:21
What I wanted is basically docker through vagga, because it's simple to set-up, lol :)
I wanted an isolated environment to compile Qt and KDE Frameworks, so the installed packages don't affect my system.

**Comment by tailhook** [comment] 2015-11-02 11:29
Sure. No problem. Just install them in `setup` and don't install in `vagga _run xxx`.

Containers are immutable by design. It's something that make vagga better than docker by default. Sometimes it makes working with them less easy. But it forces you to make important decisions earlier.

Honestly, the read-only containers are most useful for developing servers (where you should take in account every writable directory), but may be less important for desktop software. I don't know. I rarely do development for desktop.

**Comment by tailhook** [comment] 2015-11-02 20:44
There is nothing actionable left here. Feel free to open a new ticket if you have any issues.

**Closed by tailhook** 2015-11-02 20:44 UTC

**Comment by lilianmoraru** [comment] 2015-11-03 09:14
Just letting you know: I updated to the latest vagga "testing" and even the `index out of bounds` error disappeared and now I see `ERROR:vagga::wrapper: Error executing ubuntu: Command has empty "run" parameter. Nothing to run.`. I just added `run: /bin/bash` and done.
